return {
  ["workshop-1079538195"]={
    configuration_options={
      beebox=true,
      birdcage=true,
      cartographydesk=true,
      cookpot=true,
      dragonflychest=true,
      dragonflyfurnace=true,
      endtable=true,
      firesuppressor=true,
      icebox=true,
      lightning_rod=true,
      meatrack=true,
      modsupport=false,
      moondial=true,
      mushroom_farm=true,
      mushroom_light=true,
      nightlight=true,
      perdshrine=true,
      pottedfern=true,
      rainometer=true,
      researchlab=true,
      researchlab2=true,
      researchlab3=true,
      researchlab4=true,
      resurrectionstatue=true,
      saltlick=true,
      scarecrow=true,
      sculptingtable=true,
      succulent_potted=true,
      townportal=true,
      treasurechest=true,
      wardrobe=true,
      winterometer=true 
    },
    enabled=true 
  },
  ["workshop-1146082006"]={
    configuration_options={ config_fuel_max=90, config_recipe=1, config_spawn_time=30 },
    enabled=true 
  },
  ["workshop-1530801499"]={
    configuration_options={ Hunger_Cost=1, Ownership=false, Sanity_Cost=1 },
    enabled=true 
  },
  ["workshop-2289662010"]={
    configuration_options={
      RAILCART_BRAKING=1,
      RAILCART_CRAFTAMOUNT=6,
      RAILCART_DAMPING=1,
      RAILCART_FIREPROOF=false,
      RAILCART_PLAYSOUND=true,
      RAILCART_SPAWNSMOKE=true,
      RAILCART_SPEEDUP=1 
    },
    enabled=true 
  },
  ["workshop-347079953"]={
    configuration_options={ DFV_Language="CN", DFV_MinimalMode="on" },
    enabled=true 
  },
  ["workshop-350811795"]={ configuration_options={  }, enabled=true },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=99 }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-385006082"]={
    configuration_options={ [""]=0, FueledLights="no", light_color="color1", path_lightrecipe="easy" },
    enabled=true 
  },
  ["workshop-458587300"]={ configuration_options={ Ownership=false, Travel_Cost=64 }, enabled=true },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true 
    },
    enabled=true 
  },
  ["workshop-569043634"]={
    configuration_options={
      Health_Penalty_Generic="Unchanged",
      Health_Penalty_Maximum="Unchanged",
      Health_Penalty_Meat_Effigy="Unchanged",
      Health_Penalty_Portal="Unchanged",
      Health_Respawn_Amount="Unchanged",
      KeepInventory="Unchanged",
      KillMe="Unchanged",
      NoPlayerSkeletons="Unchanged",
      ReturnHotkey="Unchanged",
      ReturnHotkey_Mode="Closest",
      SpawnProtection="Unchanged",
      campfire="Enabled",
      coldfire="Enabled",
      coldfirepit="Enabled",
      firepit="Enabled",
      reviver="Unchanged",
      skeleton="Unchanged",
      usetags="Unchanged" 
    },
    enabled=true 
  },
  ["workshop-604761020"]={
    configuration_options={
      RUOYINXIAN=false,
      SHENGDANSHI=false,
      baoshibaolv=1,
      blue_baoshi=1,
      er_shuoming=0,
      green_baoshi=1,
      huangjinbaolv=1,
      marble_suipian=1,
      orange_baoshi=1,
      purple_baoshi=1,
      red_baoshi=1,
      shishengzhang=0,
      shitoubaolv=1,
      thulecite_xiukuang=1,
      wajuecishu=2,
      yellow_baoshi=1,
      yi_shuoming=0 
    },
    enabled=true 
  },
  ["workshop-623749604"]={
    configuration_options={
      Craft="Normal",
      Destroyable="DestroyByPlayer",
      FoodSpoilage=0.85,
      Language="TCh",
      Position="Center",
      Slots=80 
    },
    enabled=true 
  },
  ["workshop-661253977"]={
    configuration_options={ amudiao=true, baodiao=1, kong=0, nillots=0, rendiao=2, zbdiao=true },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-786556008"]={
    configuration_options={ ENABLEBACKPACK=false, EXTRASLOT=3, INVENTORYSIZE=45 },
    enabled=true 
  },
  ["workshop-791838548"]={
    configuration_options={
      Building_SD=33,
      Buildings=0,
      Dispenser=0,
      Dispenser_Difficulty="default",
      EHat_Difficulty="default",
      Scrap_Difficulty="default",
      ["Sentry Gun"]=0,
      Sentry_Damage=10,
      Sentry_Difficulty="default",
      Sentry_Health=200,
      Sentry_ROF=1,
      Sentry_Range=13,
      Teleporter_Difficulty="default",
      Teleporters=0,
      ["The Engineer"]=0,
      Tools=0,
      building_upgradeable="y",
      buildinglimit="y",
      dispenseramount=4,
      dispenserhealingrate=3,
      dispenserlimit="y",
      disprange=3,
      ehardhatdura=295,
      engiedmgdebuff=0.8,
      engiesciencebonus=1,
      engineer_health=125,
      engineer_hunger=150,
      engineer_sanity=200,
      eteleport_penalty=5,
      hardhatabsorb=0.7,
      pda_Difficulty="default",
      pda_ingredientpercent=0.9,
      sentry_ff="noff",
      sentry_ff_wall="noff",
      sentry_healinghit=10,
      sentryamount=4,
      sentryh_regen="n",
      sentrylimit="y",
      starting_scrap="y",
      teleporteramount=4,
      teleporterlimit="y",
      tf2Wrench_Difficulty="default",
      tf2wrenchdmg=17,
      tf2wrenchuses=150,
      toolbox_penalty=0.15 
    },
    enabled=true 
  },
  ["workshop-816057392"]={
    configuration_options={
      FLIPMOON=false,
      HIDECAVECLOCK=false,
      HUDSCALEFACTOR=100,
      SEASONOPTIONS="Clock",
      SHOWBEAVERNESS=true,
      SHOWCLOCKTEXT=true,
      SHOWMAXONNUMBERS=true,
      SHOWMOON=1,
      SHOWNAUGHTINESS=true,
      SHOWNEXTFULLMOON=true,
      SHOWSTATNUMBERS=true,
      SHOWTEMPBADGES=true,
      SHOWTEMPERATURE=true,
      SHOWWANINGMOON=true,
      SHOWWORLDTEMP=false,
      UNIT="T" 
    },
    enabled=true 
  } 
}